(cl:in-package rosflight_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TIME_OF_WEEK-VAL
          TIME_OF_WEEK
          YEAR-VAL
          YEAR
          MONTH-VAL
          MONTH
          DAY-VAL
          DAY
          HOUR-VAL
          HOUR
          MIN-VAL
          MIN
          SEC-VAL
          SEC
          VALID-VAL
          VALID
          T_ACC-VAL
          T_ACC
          NANO-VAL
          NANO
          FIX_TYPE-VAL
          FIX_TYPE
          NUM_SAT-VAL
          NUM_SAT
          LON-VAL
          LON
          LAT-VAL
          LAT
          HEIGHT-VAL
          HEIGHT
          HEIGHT_MSL-VAL
          HEIGHT_MSL
          H_ACC-VAL
          H_ACC
          V_ACC-VAL
          V_ACC
          VEL_N-VAL
          VEL_N
          VEL_E-VAL
          VEL_E
          VEL_D-VAL
          VEL_D
          G_SPEED-VAL
          G_SPEED
          HEAD_MOT-VAL
          HEAD_MOT
          S_ACC-VAL
          S_ACC
          HEAD_ACC-VAL
          HEAD_ACC
          P_DOP-VAL
          P_DOP
))