// Generated by gencpp from file rosflight_msgs/Airspeed.msg
// DO NOT EDIT!


#ifndef ROSFLIGHT_MSGS_MESSAGE_AIRSPEED_H
#define ROSFLIGHT_MSGS_MESSAGE_AIRSPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rosflight_msgs
{
template <class ContainerAllocator>
struct Airspeed_
{
  typedef Airspeed_<ContainerAllocator> Type;

  Airspeed_()
    : header()
    , velocity(0.0)
    , differential_pressure(0.0)
    , temperature(0.0)  {
    }
  Airspeed_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , velocity(0.0)
    , differential_pressure(0.0)
    , temperature(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _velocity_type;
  _velocity_type velocity;

   typedef float _differential_pressure_type;
  _differential_pressure_type differential_pressure;

   typedef float _temperature_type;
  _temperature_type temperature;





  typedef boost::shared_ptr< ::rosflight_msgs::Airspeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosflight_msgs::Airspeed_<ContainerAllocator> const> ConstPtr;

}; // struct Airspeed_

typedef ::rosflight_msgs::Airspeed_<std::allocator<void> > Airspeed;

typedef boost::shared_ptr< ::rosflight_msgs::Airspeed > AirspeedPtr;
typedef boost::shared_ptr< ::rosflight_msgs::Airspeed const> AirspeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosflight_msgs::Airspeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosflight_msgs::Airspeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosflight_msgs::Airspeed_<ContainerAllocator1> & lhs, const ::rosflight_msgs::Airspeed_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.velocity == rhs.velocity &&
    lhs.differential_pressure == rhs.differential_pressure &&
    lhs.temperature == rhs.temperature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosflight_msgs::Airspeed_<ContainerAllocator1> & lhs, const ::rosflight_msgs::Airspeed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosflight_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosflight_msgs::Airspeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosflight_msgs::Airspeed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosflight_msgs::Airspeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosflight_msgs::Airspeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosflight_msgs::Airspeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosflight_msgs::Airspeed_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosflight_msgs::Airspeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d085b3a5f8eeedfe9115165a08be6e9";
  }

  static const char* value(const ::rosflight_msgs::Airspeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d085b3a5f8eeedfULL;
  static const uint64_t static_value2 = 0xe9115165a08be6e9ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosflight_msgs::Airspeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosflight_msgs/Airspeed";
  }

  static const char* value(const ::rosflight_msgs::Airspeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosflight_msgs::Airspeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 velocity # m/s\n"
"float32 differential_pressure # Pa\n"
"float32 temperature # K\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rosflight_msgs::Airspeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosflight_msgs::Airspeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.velocity);
      stream.next(m.differential_pressure);
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Airspeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosflight_msgs::Airspeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosflight_msgs::Airspeed_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "differential_pressure: ";
    Printer<float>::stream(s, indent + "  ", v.differential_pressure);
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSFLIGHT_MSGS_MESSAGE_AIRSPEED_H
