// Generated by gencpp from file rosflight_msgs/AuxCommand.msg
// DO NOT EDIT!


#ifndef ROSFLIGHT_MSGS_MESSAGE_AUXCOMMAND_H
#define ROSFLIGHT_MSGS_MESSAGE_AUXCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rosflight_msgs
{
template <class ContainerAllocator>
struct AuxCommand_
{
  typedef AuxCommand_<ContainerAllocator> Type;

  AuxCommand_()
    : header()
    , type_array()
    , values()  {
      type_array.assign(0);

      values.assign(0.0);
  }
  AuxCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , type_array()
    , values()  {
  (void)_alloc;
      type_array.assign(0);

      values.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<uint8_t, 14>  _type_array_type;
  _type_array_type type_array;

   typedef boost::array<float, 14>  _values_type;
  _values_type values;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(AUX_COMMAND_DISABLED)
  #undef AUX_COMMAND_DISABLED
#endif
#if defined(_WIN32) && defined(AUX_COMMAND_SERVO)
  #undef AUX_COMMAND_SERVO
#endif
#if defined(_WIN32) && defined(AUX_COMMAND_MOTOR)
  #undef AUX_COMMAND_MOTOR
#endif

  enum {
    AUX_COMMAND_DISABLED = 0u,
    AUX_COMMAND_SERVO = 1u,
    AUX_COMMAND_MOTOR = 2u,
  };


  typedef boost::shared_ptr< ::rosflight_msgs::AuxCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosflight_msgs::AuxCommand_<ContainerAllocator> const> ConstPtr;

}; // struct AuxCommand_

typedef ::rosflight_msgs::AuxCommand_<std::allocator<void> > AuxCommand;

typedef boost::shared_ptr< ::rosflight_msgs::AuxCommand > AuxCommandPtr;
typedef boost::shared_ptr< ::rosflight_msgs::AuxCommand const> AuxCommandConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosflight_msgs::AuxCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosflight_msgs::AuxCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosflight_msgs::AuxCommand_<ContainerAllocator1> & lhs, const ::rosflight_msgs::AuxCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.type_array == rhs.type_array &&
    lhs.values == rhs.values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosflight_msgs::AuxCommand_<ContainerAllocator1> & lhs, const ::rosflight_msgs::AuxCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosflight_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosflight_msgs::AuxCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosflight_msgs::AuxCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosflight_msgs::AuxCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosflight_msgs::AuxCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosflight_msgs::AuxCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosflight_msgs::AuxCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosflight_msgs::AuxCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc9d592da23d69af5c42eecb1cedcb4d";
  }

  static const char* value(const ::rosflight_msgs::AuxCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc9d592da23d69afULL;
  static const uint64_t static_value2 = 0x5c42eecb1cedcb4dULL;
};

template<class ContainerAllocator>
struct DataType< ::rosflight_msgs::AuxCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosflight_msgs/AuxCommand";
  }

  static const char* value(const ::rosflight_msgs::AuxCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosflight_msgs::AuxCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Auxilliary Override Command Message\n"
"\n"
"# Command Types\n"
"uint8 AUX_COMMAND_DISABLED = 0\n"
"uint8 AUX_COMMAND_SERVO = 1\n"
"uint8 AUX_COMMAND_MOTOR = 2\n"
"\n"
"Header header\n"
"uint8[14] type_array\n"
"float32[14] values\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rosflight_msgs::AuxCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosflight_msgs::AuxCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.type_array);
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AuxCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosflight_msgs::AuxCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosflight_msgs::AuxCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "type_array[]" << std::endl;
    for (size_t i = 0; i < v.type_array.size(); ++i)
    {
      s << indent << "  type_array[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.type_array[i]);
    }
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSFLIGHT_MSGS_MESSAGE_AUXCOMMAND_H
