// Generated by gencpp from file rosflight_msgs/Barometer.msg
// DO NOT EDIT!


#ifndef ROSFLIGHT_MSGS_MESSAGE_BAROMETER_H
#define ROSFLIGHT_MSGS_MESSAGE_BAROMETER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rosflight_msgs
{
template <class ContainerAllocator>
struct Barometer_
{
  typedef Barometer_<ContainerAllocator> Type;

  Barometer_()
    : header()
    , altitude(0.0)
    , pressure(0.0)
    , temperature(0.0)  {
    }
  Barometer_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , altitude(0.0)
    , pressure(0.0)
    , temperature(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _altitude_type;
  _altitude_type altitude;

   typedef float _pressure_type;
  _pressure_type pressure;

   typedef float _temperature_type;
  _temperature_type temperature;





  typedef boost::shared_ptr< ::rosflight_msgs::Barometer_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosflight_msgs::Barometer_<ContainerAllocator> const> ConstPtr;

}; // struct Barometer_

typedef ::rosflight_msgs::Barometer_<std::allocator<void> > Barometer;

typedef boost::shared_ptr< ::rosflight_msgs::Barometer > BarometerPtr;
typedef boost::shared_ptr< ::rosflight_msgs::Barometer const> BarometerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosflight_msgs::Barometer_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosflight_msgs::Barometer_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosflight_msgs::Barometer_<ContainerAllocator1> & lhs, const ::rosflight_msgs::Barometer_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.altitude == rhs.altitude &&
    lhs.pressure == rhs.pressure &&
    lhs.temperature == rhs.temperature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosflight_msgs::Barometer_<ContainerAllocator1> & lhs, const ::rosflight_msgs::Barometer_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosflight_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosflight_msgs::Barometer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosflight_msgs::Barometer_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosflight_msgs::Barometer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosflight_msgs::Barometer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosflight_msgs::Barometer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosflight_msgs::Barometer_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosflight_msgs::Barometer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f7934988670983d230d20b43f141575";
  }

  static const char* value(const ::rosflight_msgs::Barometer_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f7934988670983dULL;
  static const uint64_t static_value2 = 0x230d20b43f141575ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosflight_msgs::Barometer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosflight_msgs/Barometer";
  }

  static const char* value(const ::rosflight_msgs::Barometer_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosflight_msgs::Barometer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 altitude\n"
"float32 pressure\n"
"float32 temperature\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rosflight_msgs::Barometer_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosflight_msgs::Barometer_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.altitude);
      stream.next(m.pressure);
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Barometer_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosflight_msgs::Barometer_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosflight_msgs::Barometer_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "altitude: ";
    Printer<float>::stream(s, indent + "  ", v.altitude);
    s << indent << "pressure: ";
    Printer<float>::stream(s, indent + "  ", v.pressure);
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSFLIGHT_MSGS_MESSAGE_BAROMETER_H
