// Generated by gencpp from file rosflight_msgs/Error.msg
// DO NOT EDIT!


#ifndef ROSFLIGHT_MSGS_MESSAGE_ERROR_H
#define ROSFLIGHT_MSGS_MESSAGE_ERROR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rosflight_msgs
{
template <class ContainerAllocator>
struct Error_
{
  typedef Error_<ContainerAllocator> Type;

  Error_()
    : header()
    , error_message()
    , error_code(0)
    , reset_count(0)
    , rearm(false)
    , pc(0)  {
    }
  Error_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , error_message(_alloc)
    , error_code(0)
    , reset_count(0)
    , rearm(false)
    , pc(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_message_type;
  _error_message_type error_message;

   typedef uint32_t _error_code_type;
  _error_code_type error_code;

   typedef uint32_t _reset_count_type;
  _reset_count_type reset_count;

   typedef uint8_t _rearm_type;
  _rearm_type rearm;

   typedef uint32_t _pc_type;
  _pc_type pc;





  typedef boost::shared_ptr< ::rosflight_msgs::Error_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosflight_msgs::Error_<ContainerAllocator> const> ConstPtr;

}; // struct Error_

typedef ::rosflight_msgs::Error_<std::allocator<void> > Error;

typedef boost::shared_ptr< ::rosflight_msgs::Error > ErrorPtr;
typedef boost::shared_ptr< ::rosflight_msgs::Error const> ErrorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosflight_msgs::Error_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosflight_msgs::Error_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosflight_msgs::Error_<ContainerAllocator1> & lhs, const ::rosflight_msgs::Error_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.error_message == rhs.error_message &&
    lhs.error_code == rhs.error_code &&
    lhs.reset_count == rhs.reset_count &&
    lhs.rearm == rhs.rearm &&
    lhs.pc == rhs.pc;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosflight_msgs::Error_<ContainerAllocator1> & lhs, const ::rosflight_msgs::Error_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosflight_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosflight_msgs::Error_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosflight_msgs::Error_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosflight_msgs::Error_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosflight_msgs::Error_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosflight_msgs::Error_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosflight_msgs::Error_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosflight_msgs::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54b4d1e0725009401e6c34324c30bd0f";
  }

  static const char* value(const ::rosflight_msgs::Error_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54b4d1e072500940ULL;
  static const uint64_t static_value2 = 0x1e6c34324c30bd0fULL;
};

template<class ContainerAllocator>
struct DataType< ::rosflight_msgs::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosflight_msgs/Error";
  }

  static const char* value(const ::rosflight_msgs::Error_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosflight_msgs::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#For handling rosflight hard errors\n"
"\n"
"Header header\n"
"string error_message\n"
"uint32 error_code\n"
"uint32 reset_count\n"
"bool rearm\n"
"uint32 pc\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rosflight_msgs::Error_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosflight_msgs::Error_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.error_message);
      stream.next(m.error_code);
      stream.next(m.reset_count);
      stream.next(m.rearm);
      stream.next(m.pc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Error_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosflight_msgs::Error_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosflight_msgs::Error_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "error_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_message);
    s << indent << "error_code: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "reset_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.reset_count);
    s << indent << "rearm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rearm);
    s << indent << "pc: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.pc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSFLIGHT_MSGS_MESSAGE_ERROR_H
