// Generated by gencpp from file rosflight_msgs/OutputRaw.msg
// DO NOT EDIT!


#ifndef ROSFLIGHT_MSGS_MESSAGE_OUTPUTRAW_H
#define ROSFLIGHT_MSGS_MESSAGE_OUTPUTRAW_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rosflight_msgs
{
template <class ContainerAllocator>
struct OutputRaw_
{
  typedef OutputRaw_<ContainerAllocator> Type;

  OutputRaw_()
    : header()
    , values()  {
      values.assign(0.0);
  }
  OutputRaw_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , values()  {
  (void)_alloc;
      values.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 14>  _values_type;
  _values_type values;





  typedef boost::shared_ptr< ::rosflight_msgs::OutputRaw_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosflight_msgs::OutputRaw_<ContainerAllocator> const> ConstPtr;

}; // struct OutputRaw_

typedef ::rosflight_msgs::OutputRaw_<std::allocator<void> > OutputRaw;

typedef boost::shared_ptr< ::rosflight_msgs::OutputRaw > OutputRawPtr;
typedef boost::shared_ptr< ::rosflight_msgs::OutputRaw const> OutputRawConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosflight_msgs::OutputRaw_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosflight_msgs::OutputRaw_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosflight_msgs::OutputRaw_<ContainerAllocator1> & lhs, const ::rosflight_msgs::OutputRaw_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.values == rhs.values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosflight_msgs::OutputRaw_<ContainerAllocator1> & lhs, const ::rosflight_msgs::OutputRaw_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosflight_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosflight_msgs::OutputRaw_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosflight_msgs::OutputRaw_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosflight_msgs::OutputRaw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosflight_msgs::OutputRaw_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosflight_msgs::OutputRaw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosflight_msgs::OutputRaw_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosflight_msgs::OutputRaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86704c636f24b54825756571c5e852f0";
  }

  static const char* value(const ::rosflight_msgs::OutputRaw_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86704c636f24b548ULL;
  static const uint64_t static_value2 = 0x25756571c5e852f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosflight_msgs::OutputRaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosflight_msgs/OutputRaw";
  }

  static const char* value(const ::rosflight_msgs::OutputRaw_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosflight_msgs::OutputRaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# raw servo outputs\n"
"\n"
"Header header\n"
"float32[14] values\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rosflight_msgs::OutputRaw_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosflight_msgs::OutputRaw_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OutputRaw_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosflight_msgs::OutputRaw_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosflight_msgs::OutputRaw_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSFLIGHT_MSGS_MESSAGE_OUTPUTRAW_H
