// Generated by gencpp from file rosflight_msgs/ParamFile.msg
// DO NOT EDIT!


#ifndef ROSFLIGHT_MSGS_MESSAGE_PARAMFILE_H
#define ROSFLIGHT_MSGS_MESSAGE_PARAMFILE_H

#include <ros/service_traits.h>


#include <rosflight_msgs/ParamFileRequest.h>
#include <rosflight_msgs/ParamFileResponse.h>


namespace rosflight_msgs
{

struct ParamFile
{

typedef ParamFileRequest Request;
typedef ParamFileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ParamFile
} // namespace rosflight_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosflight_msgs::ParamFile > {
  static const char* value()
  {
    return "93a4bc4c60dc17e2a69e3fcaaa25d69d";
  }

  static const char* value(const ::rosflight_msgs::ParamFile&) { return value(); }
};

template<>
struct DataType< ::rosflight_msgs::ParamFile > {
  static const char* value()
  {
    return "rosflight_msgs/ParamFile";
  }

  static const char* value(const ::rosflight_msgs::ParamFile&) { return value(); }
};


// service_traits::MD5Sum< ::rosflight_msgs::ParamFileRequest> should match
// service_traits::MD5Sum< ::rosflight_msgs::ParamFile >
template<>
struct MD5Sum< ::rosflight_msgs::ParamFileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosflight_msgs::ParamFile >::value();
  }
  static const char* value(const ::rosflight_msgs::ParamFileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosflight_msgs::ParamFileRequest> should match
// service_traits::DataType< ::rosflight_msgs::ParamFile >
template<>
struct DataType< ::rosflight_msgs::ParamFileRequest>
{
  static const char* value()
  {
    return DataType< ::rosflight_msgs::ParamFile >::value();
  }
  static const char* value(const ::rosflight_msgs::ParamFileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosflight_msgs::ParamFileResponse> should match
// service_traits::MD5Sum< ::rosflight_msgs::ParamFile >
template<>
struct MD5Sum< ::rosflight_msgs::ParamFileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosflight_msgs::ParamFile >::value();
  }
  static const char* value(const ::rosflight_msgs::ParamFileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosflight_msgs::ParamFileResponse> should match
// service_traits::DataType< ::rosflight_msgs::ParamFile >
template<>
struct DataType< ::rosflight_msgs::ParamFileResponse>
{
  static const char* value()
  {
    return DataType< ::rosflight_msgs::ParamFile >::value();
  }
  static const char* value(const ::rosflight_msgs::ParamFileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSFLIGHT_MSGS_MESSAGE_PARAMFILE_H
