// Generated by gencpp from file rosflight_msgs/ParamGet.msg
// DO NOT EDIT!


#ifndef ROSFLIGHT_MSGS_MESSAGE_PARAMGET_H
#define ROSFLIGHT_MSGS_MESSAGE_PARAMGET_H

#include <ros/service_traits.h>


#include <rosflight_msgs/ParamGetRequest.h>
#include <rosflight_msgs/ParamGetResponse.h>


namespace rosflight_msgs
{

struct ParamGet
{

typedef ParamGetRequest Request;
typedef ParamGetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ParamGet
} // namespace rosflight_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosflight_msgs::ParamGet > {
  static const char* value()
  {
    return "084c270cbd1d72e2f34b8b8b23df1ede";
  }

  static const char* value(const ::rosflight_msgs::ParamGet&) { return value(); }
};

template<>
struct DataType< ::rosflight_msgs::ParamGet > {
  static const char* value()
  {
    return "rosflight_msgs/ParamGet";
  }

  static const char* value(const ::rosflight_msgs::ParamGet&) { return value(); }
};


// service_traits::MD5Sum< ::rosflight_msgs::ParamGetRequest> should match
// service_traits::MD5Sum< ::rosflight_msgs::ParamGet >
template<>
struct MD5Sum< ::rosflight_msgs::ParamGetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosflight_msgs::ParamGet >::value();
  }
  static const char* value(const ::rosflight_msgs::ParamGetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosflight_msgs::ParamGetRequest> should match
// service_traits::DataType< ::rosflight_msgs::ParamGet >
template<>
struct DataType< ::rosflight_msgs::ParamGetRequest>
{
  static const char* value()
  {
    return DataType< ::rosflight_msgs::ParamGet >::value();
  }
  static const char* value(const ::rosflight_msgs::ParamGetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosflight_msgs::ParamGetResponse> should match
// service_traits::MD5Sum< ::rosflight_msgs::ParamGet >
template<>
struct MD5Sum< ::rosflight_msgs::ParamGetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosflight_msgs::ParamGet >::value();
  }
  static const char* value(const ::rosflight_msgs::ParamGetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosflight_msgs::ParamGetResponse> should match
// service_traits::DataType< ::rosflight_msgs::ParamGet >
template<>
struct DataType< ::rosflight_msgs::ParamGetResponse>
{
  static const char* value()
  {
    return DataType< ::rosflight_msgs::ParamGet >::value();
  }
  static const char* value(const ::rosflight_msgs::ParamGetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSFLIGHT_MSGS_MESSAGE_PARAMGET_H
