// Generated by gencpp from file rosflight_msgs/ParamSet.msg
// DO NOT EDIT!


#ifndef ROSFLIGHT_MSGS_MESSAGE_PARAMSET_H
#define ROSFLIGHT_MSGS_MESSAGE_PARAMSET_H

#include <ros/service_traits.h>


#include <rosflight_msgs/ParamSetRequest.h>
#include <rosflight_msgs/ParamSetResponse.h>


namespace rosflight_msgs
{

struct ParamSet
{

typedef ParamSetRequest Request;
typedef ParamSetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ParamSet
} // namespace rosflight_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosflight_msgs::ParamSet > {
  static const char* value()
  {
    return "39d2a767f6a7b381c122060d7b56567b";
  }

  static const char* value(const ::rosflight_msgs::ParamSet&) { return value(); }
};

template<>
struct DataType< ::rosflight_msgs::ParamSet > {
  static const char* value()
  {
    return "rosflight_msgs/ParamSet";
  }

  static const char* value(const ::rosflight_msgs::ParamSet&) { return value(); }
};


// service_traits::MD5Sum< ::rosflight_msgs::ParamSetRequest> should match
// service_traits::MD5Sum< ::rosflight_msgs::ParamSet >
template<>
struct MD5Sum< ::rosflight_msgs::ParamSetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosflight_msgs::ParamSet >::value();
  }
  static const char* value(const ::rosflight_msgs::ParamSetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosflight_msgs::ParamSetRequest> should match
// service_traits::DataType< ::rosflight_msgs::ParamSet >
template<>
struct DataType< ::rosflight_msgs::ParamSetRequest>
{
  static const char* value()
  {
    return DataType< ::rosflight_msgs::ParamSet >::value();
  }
  static const char* value(const ::rosflight_msgs::ParamSetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosflight_msgs::ParamSetResponse> should match
// service_traits::MD5Sum< ::rosflight_msgs::ParamSet >
template<>
struct MD5Sum< ::rosflight_msgs::ParamSetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosflight_msgs::ParamSet >::value();
  }
  static const char* value(const ::rosflight_msgs::ParamSetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosflight_msgs::ParamSetResponse> should match
// service_traits::DataType< ::rosflight_msgs::ParamSet >
template<>
struct DataType< ::rosflight_msgs::ParamSetResponse>
{
  static const char* value()
  {
    return DataType< ::rosflight_msgs::ParamSet >::value();
  }
  static const char* value(const ::rosflight_msgs::ParamSetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSFLIGHT_MSGS_MESSAGE_PARAMSET_H
