// Generated by gencpp from file rosflight_msgs/Status.msg
// DO NOT EDIT!


#ifndef ROSFLIGHT_MSGS_MESSAGE_STATUS_H
#define ROSFLIGHT_MSGS_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rosflight_msgs
{
template <class ContainerAllocator>
struct Status_
{
  typedef Status_<ContainerAllocator> Type;

  Status_()
    : header()
    , armed(false)
    , failsafe(false)
    , rc_override(false)
    , offboard(false)
    , control_mode(0)
    , error_code(0)
    , num_errors(0)
    , loop_time_us(0)  {
    }
  Status_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , armed(false)
    , failsafe(false)
    , rc_override(false)
    , offboard(false)
    , control_mode(0)
    , error_code(0)
    , num_errors(0)
    , loop_time_us(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _armed_type;
  _armed_type armed;

   typedef uint8_t _failsafe_type;
  _failsafe_type failsafe;

   typedef uint8_t _rc_override_type;
  _rc_override_type rc_override;

   typedef uint8_t _offboard_type;
  _offboard_type offboard;

   typedef int8_t _control_mode_type;
  _control_mode_type control_mode;

   typedef int8_t _error_code_type;
  _error_code_type error_code;

   typedef int16_t _num_errors_type;
  _num_errors_type num_errors;

   typedef int16_t _loop_time_us_type;
  _loop_time_us_type loop_time_us;





  typedef boost::shared_ptr< ::rosflight_msgs::Status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosflight_msgs::Status_<ContainerAllocator> const> ConstPtr;

}; // struct Status_

typedef ::rosflight_msgs::Status_<std::allocator<void> > Status;

typedef boost::shared_ptr< ::rosflight_msgs::Status > StatusPtr;
typedef boost::shared_ptr< ::rosflight_msgs::Status const> StatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosflight_msgs::Status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosflight_msgs::Status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosflight_msgs::Status_<ContainerAllocator1> & lhs, const ::rosflight_msgs::Status_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.armed == rhs.armed &&
    lhs.failsafe == rhs.failsafe &&
    lhs.rc_override == rhs.rc_override &&
    lhs.offboard == rhs.offboard &&
    lhs.control_mode == rhs.control_mode &&
    lhs.error_code == rhs.error_code &&
    lhs.num_errors == rhs.num_errors &&
    lhs.loop_time_us == rhs.loop_time_us;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosflight_msgs::Status_<ContainerAllocator1> & lhs, const ::rosflight_msgs::Status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosflight_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosflight_msgs::Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosflight_msgs::Status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosflight_msgs::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosflight_msgs::Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosflight_msgs::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosflight_msgs::Status_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosflight_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47d8a47dbe4d0941ff4c84b89a5de11e";
  }

  static const char* value(const ::rosflight_msgs::Status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47d8a47dbe4d0941ULL;
  static const uint64_t static_value2 = 0xff4c84b89a5de11eULL;
};

template<class ContainerAllocator>
struct DataType< ::rosflight_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosflight_msgs/Status";
  }

  static const char* value(const ::rosflight_msgs::Status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosflight_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Flight controller status message\n"
"\n"
"Header header\n"
"\n"
"bool armed         # True if armed\n"
"bool failsafe      # True if in failsafe\n"
"bool rc_override   # True if RC is in control\n"
"bool offboard      # True if offboard control is active\n"
"int8 control_mode  # Onboard control mode\n"
"int8 error_code    # Onboard error code\n"
"int16 num_errors   # Number of errors\n"
"int16 loop_time_us # Loop time in microseconds\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rosflight_msgs::Status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosflight_msgs::Status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.armed);
      stream.next(m.failsafe);
      stream.next(m.rc_override);
      stream.next(m.offboard);
      stream.next(m.control_mode);
      stream.next(m.error_code);
      stream.next(m.num_errors);
      stream.next(m.loop_time_us);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosflight_msgs::Status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosflight_msgs::Status_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "armed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.armed);
    s << indent << "failsafe: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.failsafe);
    s << indent << "rc_override: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rc_override);
    s << indent << "offboard: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.offboard);
    s << indent << "control_mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.control_mode);
    s << indent << "error_code: ";
    Printer<int8_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "num_errors: ";
    Printer<int16_t>::stream(s, indent + "  ", v.num_errors);
    s << indent << "loop_time_us: ";
    Printer<int16_t>::stream(s, indent + "  ", v.loop_time_us);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSFLIGHT_MSGS_MESSAGE_STATUS_H
