// Generated by gencpp from file rosplane_msgs/Controller_Internals.msg
// DO NOT EDIT!


#ifndef ROSPLANE_MSGS_MESSAGE_CONTROLLER_INTERNALS_H
#define ROSPLANE_MSGS_MESSAGE_CONTROLLER_INTERNALS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosplane_msgs
{
template <class ContainerAllocator>
struct Controller_Internals_
{
  typedef Controller_Internals_<ContainerAllocator> Type;

  Controller_Internals_()
    : theta_c(0.0)
    , phi_c(0.0)
    , alt_zone(0)
    , aux()
    , aux_valid(false)  {
      aux.assign(0.0);
  }
  Controller_Internals_(const ContainerAllocator& _alloc)
    : theta_c(0.0)
    , phi_c(0.0)
    , alt_zone(0)
    , aux()
    , aux_valid(false)  {
  (void)_alloc;
      aux.assign(0.0);
  }



   typedef float _theta_c_type;
  _theta_c_type theta_c;

   typedef float _phi_c_type;
  _phi_c_type phi_c;

   typedef uint8_t _alt_zone_type;
  _alt_zone_type alt_zone;

   typedef boost::array<float, 4>  _aux_type;
  _aux_type aux;

   typedef uint8_t _aux_valid_type;
  _aux_valid_type aux_valid;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(ZONE_TAKE_OFF)
  #undef ZONE_TAKE_OFF
#endif
#if defined(_WIN32) && defined(ZONE_CLIMB)
  #undef ZONE_CLIMB
#endif
#if defined(_WIN32) && defined(ZONE_DESEND)
  #undef ZONE_DESEND
#endif
#if defined(_WIN32) && defined(ZONE_ALTITUDE_HOLD)
  #undef ZONE_ALTITUDE_HOLD
#endif

  enum {
    ZONE_TAKE_OFF = 0u,
    ZONE_CLIMB = 1u,
    ZONE_DESEND = 2u,
    ZONE_ALTITUDE_HOLD = 3u,
  };


  typedef boost::shared_ptr< ::rosplane_msgs::Controller_Internals_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosplane_msgs::Controller_Internals_<ContainerAllocator> const> ConstPtr;

}; // struct Controller_Internals_

typedef ::rosplane_msgs::Controller_Internals_<std::allocator<void> > Controller_Internals;

typedef boost::shared_ptr< ::rosplane_msgs::Controller_Internals > Controller_InternalsPtr;
typedef boost::shared_ptr< ::rosplane_msgs::Controller_Internals const> Controller_InternalsConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosplane_msgs::Controller_Internals_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosplane_msgs::Controller_Internals_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosplane_msgs::Controller_Internals_<ContainerAllocator1> & lhs, const ::rosplane_msgs::Controller_Internals_<ContainerAllocator2> & rhs)
{
  return lhs.theta_c == rhs.theta_c &&
    lhs.phi_c == rhs.phi_c &&
    lhs.alt_zone == rhs.alt_zone &&
    lhs.aux == rhs.aux &&
    lhs.aux_valid == rhs.aux_valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosplane_msgs::Controller_Internals_<ContainerAllocator1> & lhs, const ::rosplane_msgs::Controller_Internals_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosplane_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosplane_msgs::Controller_Internals_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosplane_msgs::Controller_Internals_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplane_msgs::Controller_Internals_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplane_msgs::Controller_Internals_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplane_msgs::Controller_Internals_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplane_msgs::Controller_Internals_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosplane_msgs::Controller_Internals_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d7fa61846cd31497d4b102451fa214b";
  }

  static const char* value(const ::rosplane_msgs::Controller_Internals_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d7fa61846cd3149ULL;
  static const uint64_t static_value2 = 0x7d4b102451fa214bULL;
};

template<class ContainerAllocator>
struct DataType< ::rosplane_msgs::Controller_Internals_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosplane_msgs/Controller_Internals";
  }

  static const char* value(const ::rosplane_msgs::Controller_Internals_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosplane_msgs::Controller_Internals_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Controller internals (inner loops, states) output from the autopilot controller, for now just for debuging and ploting\n"
"\n"
"# @warning theta_c, phi_c and alt_zone have always to be valid, the aux array is optional\n"
"float32 theta_c		# Commanded pitch (rad)\n"
"float32 phi_c		# Commanded roll (rad)\n"
"uint8 alt_zone		# Zone in the altitude state machine\n"
"float32[4] aux		# Optional auxiliary commands\n"
"bool aux_valid		# Auxiliary commands valid\n"
"\n"
"uint8 ZONE_TAKE_OFF = 0\n"
"uint8 ZONE_CLIMB = 1\n"
"uint8 ZONE_DESEND = 2\n"
"uint8 ZONE_ALTITUDE_HOLD = 3\n"
;
  }

  static const char* value(const ::rosplane_msgs::Controller_Internals_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosplane_msgs::Controller_Internals_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.theta_c);
      stream.next(m.phi_c);
      stream.next(m.alt_zone);
      stream.next(m.aux);
      stream.next(m.aux_valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Controller_Internals_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosplane_msgs::Controller_Internals_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosplane_msgs::Controller_Internals_<ContainerAllocator>& v)
  {
    s << indent << "theta_c: ";
    Printer<float>::stream(s, indent + "  ", v.theta_c);
    s << indent << "phi_c: ";
    Printer<float>::stream(s, indent + "  ", v.phi_c);
    s << indent << "alt_zone: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.alt_zone);
    s << indent << "aux[]" << std::endl;
    for (size_t i = 0; i < v.aux.size(); ++i)
    {
      s << indent << "  aux[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.aux[i]);
    }
    s << indent << "aux_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.aux_valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPLANE_MSGS_MESSAGE_CONTROLLER_INTERNALS_H
