// Generated by gencpp from file rosplane_msgs/State.msg
// DO NOT EDIT!


#ifndef ROSPLANE_MSGS_MESSAGE_STATE_H
#define ROSPLANE_MSGS_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rosplane_msgs
{
template <class ContainerAllocator>
struct State_
{
  typedef State_<ContainerAllocator> Type;

  State_()
    : header()
    , position()
    , Va(0.0)
    , alpha(0.0)
    , beta(0.0)
    , phi(0.0)
    , theta(0.0)
    , psi(0.0)
    , chi(0.0)
    , p(0.0)
    , q(0.0)
    , r(0.0)
    , Vg(0.0)
    , wn(0.0)
    , we(0.0)
    , quat()
    , quat_valid(false)
    , chi_deg(0.0)
    , psi_deg(0.0)
    , initial_lat(0.0)
    , initial_lon(0.0)
    , initial_alt(0.0)  {
      position.assign(0.0);

      quat.assign(0.0);
  }
  State_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position()
    , Va(0.0)
    , alpha(0.0)
    , beta(0.0)
    , phi(0.0)
    , theta(0.0)
    , psi(0.0)
    , chi(0.0)
    , p(0.0)
    , q(0.0)
    , r(0.0)
    , Vg(0.0)
    , wn(0.0)
    , we(0.0)
    , quat()
    , quat_valid(false)
    , chi_deg(0.0)
    , psi_deg(0.0)
    , initial_lat(0.0)
    , initial_lon(0.0)
    , initial_alt(0.0)  {
  (void)_alloc;
      position.assign(0.0);

      quat.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 3>  _position_type;
  _position_type position;

   typedef float _Va_type;
  _Va_type Va;

   typedef float _alpha_type;
  _alpha_type alpha;

   typedef float _beta_type;
  _beta_type beta;

   typedef float _phi_type;
  _phi_type phi;

   typedef float _theta_type;
  _theta_type theta;

   typedef float _psi_type;
  _psi_type psi;

   typedef float _chi_type;
  _chi_type chi;

   typedef float _p_type;
  _p_type p;

   typedef float _q_type;
  _q_type q;

   typedef float _r_type;
  _r_type r;

   typedef float _Vg_type;
  _Vg_type Vg;

   typedef float _wn_type;
  _wn_type wn;

   typedef float _we_type;
  _we_type we;

   typedef boost::array<float, 4>  _quat_type;
  _quat_type quat;

   typedef uint8_t _quat_valid_type;
  _quat_valid_type quat_valid;

   typedef float _chi_deg_type;
  _chi_deg_type chi_deg;

   typedef float _psi_deg_type;
  _psi_deg_type psi_deg;

   typedef float _initial_lat_type;
  _initial_lat_type initial_lat;

   typedef float _initial_lon_type;
  _initial_lon_type initial_lon;

   typedef float _initial_alt_type;
  _initial_alt_type initial_alt;





  typedef boost::shared_ptr< ::rosplane_msgs::State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosplane_msgs::State_<ContainerAllocator> const> ConstPtr;

}; // struct State_

typedef ::rosplane_msgs::State_<std::allocator<void> > State;

typedef boost::shared_ptr< ::rosplane_msgs::State > StatePtr;
typedef boost::shared_ptr< ::rosplane_msgs::State const> StateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosplane_msgs::State_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosplane_msgs::State_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosplane_msgs::State_<ContainerAllocator1> & lhs, const ::rosplane_msgs::State_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position &&
    lhs.Va == rhs.Va &&
    lhs.alpha == rhs.alpha &&
    lhs.beta == rhs.beta &&
    lhs.phi == rhs.phi &&
    lhs.theta == rhs.theta &&
    lhs.psi == rhs.psi &&
    lhs.chi == rhs.chi &&
    lhs.p == rhs.p &&
    lhs.q == rhs.q &&
    lhs.r == rhs.r &&
    lhs.Vg == rhs.Vg &&
    lhs.wn == rhs.wn &&
    lhs.we == rhs.we &&
    lhs.quat == rhs.quat &&
    lhs.quat_valid == rhs.quat_valid &&
    lhs.chi_deg == rhs.chi_deg &&
    lhs.psi_deg == rhs.psi_deg &&
    lhs.initial_lat == rhs.initial_lat &&
    lhs.initial_lon == rhs.initial_lon &&
    lhs.initial_alt == rhs.initial_alt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosplane_msgs::State_<ContainerAllocator1> & lhs, const ::rosplane_msgs::State_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosplane_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosplane_msgs::State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosplane_msgs::State_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplane_msgs::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplane_msgs::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplane_msgs::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplane_msgs::State_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosplane_msgs::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57224b7ced1a3b169bed04d7cbeefdfe";
  }

  static const char* value(const ::rosplane_msgs::State_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57224b7ced1a3b16ULL;
  static const uint64_t static_value2 = 0x9bed04d7cbeefdfeULL;
};

template<class ContainerAllocator>
struct DataType< ::rosplane_msgs::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosplane_msgs/State";
  }

  static const char* value(const ::rosplane_msgs::State_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosplane_msgs::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Vehicle state 'x_hat' output from the estimator or from simulator \n"
"\n"
"Header header\n"
"\n"
"# Original States\n"
"# @warning roll, pitch and yaw have always to be valid, the quaternion is optional\n"
"float32[3] position	# north, east, down (m)\n"
"float32 Va		# Airspeed (m/s)\n"
"float32 alpha		# Angle of attack (rad)\n"
"float32 beta		# Slide slip angle (rad)\n"
"float32 phi		# Roll angle (rad)\n"
"float32 theta		# Pitch angle (rad)\n"
"float32 psi		# Yaw angle (rad)\n"
"float32 chi		# Course angle (rad)\n"
"float32 p		# Body frame rollrate (rad/s)\n"
"float32 q		# Body frame pitchrate (rad/s)\n"
"float32 r		# Body frame yawrate (rad/s)\n"
"float32 Vg		# Groundspeed (m/s)\n"
"float32 wn		# Windspeed north component (m/s)\n"
"float32 we		# Windspeed east component (m/s)\n"
"\n"
"# Additional States for convenience\n"
"float32[4] quat		# Quaternion (wxyz, NED)\n"
"bool quat_valid		# Quaternion valid\n"
"float32 chi_deg		# Wrapped course angle (deg)\n"
"float32 psi_deg		# Wrapped yaw angle (deg)\n"
"float32 initial_lat 	# Initial/origin latitude (lat. deg)\n"
"float32 initial_lon 	# Initial/origin longitude (lon. deg) \n"
"float32 initial_alt 	# Initial/origin altitude (m) \n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rosplane_msgs::State_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosplane_msgs::State_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.Va);
      stream.next(m.alpha);
      stream.next(m.beta);
      stream.next(m.phi);
      stream.next(m.theta);
      stream.next(m.psi);
      stream.next(m.chi);
      stream.next(m.p);
      stream.next(m.q);
      stream.next(m.r);
      stream.next(m.Vg);
      stream.next(m.wn);
      stream.next(m.we);
      stream.next(m.quat);
      stream.next(m.quat_valid);
      stream.next(m.chi_deg);
      stream.next(m.psi_deg);
      stream.next(m.initial_lat);
      stream.next(m.initial_lon);
      stream.next(m.initial_alt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct State_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosplane_msgs::State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosplane_msgs::State_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "Va: ";
    Printer<float>::stream(s, indent + "  ", v.Va);
    s << indent << "alpha: ";
    Printer<float>::stream(s, indent + "  ", v.alpha);
    s << indent << "beta: ";
    Printer<float>::stream(s, indent + "  ", v.beta);
    s << indent << "phi: ";
    Printer<float>::stream(s, indent + "  ", v.phi);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "psi: ";
    Printer<float>::stream(s, indent + "  ", v.psi);
    s << indent << "chi: ";
    Printer<float>::stream(s, indent + "  ", v.chi);
    s << indent << "p: ";
    Printer<float>::stream(s, indent + "  ", v.p);
    s << indent << "q: ";
    Printer<float>::stream(s, indent + "  ", v.q);
    s << indent << "r: ";
    Printer<float>::stream(s, indent + "  ", v.r);
    s << indent << "Vg: ";
    Printer<float>::stream(s, indent + "  ", v.Vg);
    s << indent << "wn: ";
    Printer<float>::stream(s, indent + "  ", v.wn);
    s << indent << "we: ";
    Printer<float>::stream(s, indent + "  ", v.we);
    s << indent << "quat[]" << std::endl;
    for (size_t i = 0; i < v.quat.size(); ++i)
    {
      s << indent << "  quat[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.quat[i]);
    }
    s << indent << "quat_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.quat_valid);
    s << indent << "chi_deg: ";
    Printer<float>::stream(s, indent + "  ", v.chi_deg);
    s << indent << "psi_deg: ";
    Printer<float>::stream(s, indent + "  ", v.psi_deg);
    s << indent << "initial_lat: ";
    Printer<float>::stream(s, indent + "  ", v.initial_lat);
    s << indent << "initial_lon: ";
    Printer<float>::stream(s, indent + "  ", v.initial_lon);
    s << indent << "initial_alt: ";
    Printer<float>::stream(s, indent + "  ", v.initial_alt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPLANE_MSGS_MESSAGE_STATE_H
