(cl:in-package rosplane_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          POSITION-VAL
          POSITION
          VA-VAL
          VA
          ALPHA-VAL
          ALPHA
          BETA-VAL
          BETA
          PHI-VAL
          PHI
          THETA-VAL
          THETA
          PSI-VAL
          PSI
          CHI-VAL
          CHI
          P-VAL
          P
          Q-VAL
          Q
          R-VAL
          R
          VG-VAL
          VG
          WN-VAL
          WN
          WE-VAL
          WE
          QUAT-VAL
          QUAT
          QUAT_VALID-VAL
          QUAT_VALID
          CHI_DEG-VAL
          CHI_DEG
          PSI_DEG-VAL
          PSI_DEG
          INITIAL_LAT-VAL
          INITIAL_LAT
          INITIAL_LON-VAL
          INITIAL_LON
          INITIAL_ALT-VAL
          INITIAL_ALT
))